package aquadig;

public final class c {
   com.vlm.redstar.client.ui.b a;
   static final String[] b = new String[]{"*", "0", "#"};
   private String ch;
   private String ci;
   private String cj;
   private String ck;
   static String c;
   static String d;
   static String e;
   static String f;
   static String g;
   static String h;
   static String i;
   static String j;
   static String k;
   static String l;
   static String m;
   static String n;
   static String o;
   static String p;
   static String q;
   static String r;
   static String s;
   static String t;
   static String u;
   static String v;
   static String w;
   static String x;
   static String y;
   static String z;
   static String A;
   static String B;
   static String C;
   static String D;
   static String E;
   static String F;
   static String G;
   static String H;
   static String I;
   static String J;
   static String K;
   static String L;
   static String M;
   static String N;
   static String O;
   static String P;
   static String Q;
   static String R;
   static String S;
   static String T;
   static String U;
   static String V;
   static String W;
   static String X;
   static String Y;
   static String Z;
   static String aa;
   static String ab;
   static String ac;
   static String ad;
   static String ae;
   static String af;
   static String ag;
   static String ah;
   static String ai;
   private String cl;
   private String cm;
   private String cn;
   private String co;
   private String cp;
   private String cq;
   private String cr;
   static String aj;
   static String ak;
   static String al;
   static String am;
   static String an;
   static String ao;
   static String ap;
   static String aq;
   static String ar;
   static String as;
   static String at;
   static String au;
   private String cs;
   private String ct;
   private String cu;
   private String cv;
   private String cw;
   private String cx;
   private String cy;
   private String cz;
   private String cA;
   private String cB;
   private String cC;
   static String av;
   private String cD;
   private String cE;
   private String cF;
   private String cG;
   private String cH;
   private String cI;
   private String cJ;
   private String cK;
   private String cL;
   private String cM;
   private String cN;
   private String cO;
   private String cP;
   private String cQ;
   private String cR;
   private String cS;
   private String cT;
   private String cU;
   private String cV;
   private String cW;
   private String cX;
   private String cY;
   private String cZ;
   private String da;
   private String db;
   private String dc;
   private String dd;
   private String de;
   private String df;
   private String dg;
   private String dh;
   private String di;
   private String dj;
   private String dk;
   private String dl;
   private String dm;
   private String dn;
   private String do_;
   static String aw;
   static String ax;
   static String ay;
   static String az;
   private String dp;
   private String dq;
   private String dr;
   private String ds;
   private String dt;
   private String du;
   private String dv;
   private String dw;
   private String dx;
   private String dy;
   private String dz;
   private String dA;
   private String dB;
   private String dC;
   private String dD;
   private String dE;
   private String dF;
   private String dG;
   private String dH;
   private String dI;
   private String dJ;
   private String dK;
   private String dL;
   private String dM;
   private String dN;
   static String aA;
   private String dO;
   private String dP;
   static String aB;
   static String aC;
   static String aD;
   static String aE;
   private String dQ;
   private String dR;
   private String dS;
   private String dT;
   private String dU;
   private String dV;
   private String dW;
   static String aF;
   static String aG;
   private String dX;
   private String dY;
   private String dZ;
   private String ea;
   private String eb;
   private String ec;
   private String ed;
   private String ee;
   static String aH;
   static String aI;
   static String aJ;
   private String ef;
   private String eg;
   private String eh;
   private String ei;
   private String ej;
   static String aK;
   static String aL;
   static String aM;
   static String aN;
   static String aO;
   static String aP;
   static String aQ;
   static String aR;
   static String aS;
   static String aT;
   static String aU;
   static String aV;
   static String aW;
   static String aX;
   static String aY;
   static String aZ;
   static String ba;
   static String bb;
   static String bc;
   static String bd;
   static String be;
   static String bf;
   static String bg;
   static String bh;
   static String bi;
   static String bj;
   static String bk;
   static String bl;
   static String bm;
   static String bn;
   static String bo;
   static String bp;
   static String bq;
   static String br;
   static String bs;
   static String bt;
   static String bu;
   static String bv;
   static String bw;
   static String bx;
   static String by;
   static String bz;
   static String bA;
   static String bB;
   static String bC;
   static String bD;
   static String bE;
   static String bF;
   static String bG;
   static String bH;
   static String bI;
   static String bJ;
   static String bK;
   static String bL;
   static String bM;
   static String[] bN;
   static String[] bO;
   static String bP;
   static String bQ;
   static String bR;
   static String bS;
   static String bT;
   static String bU;
   static String[] bV;
   static String[] bW;
   static String[] bX;
   static String[] bY;
   static String[] bZ;
   static String[] ca;
   static String[][] cb;
   static String[] cc;
   static String[] cd;
   static String[] ce;
   static String[] cf;
   static String[] cg;

   public c() {
   }

   public c(byte var1) {
      String var2;
      label18: {
         var2 = null;
         String var10000;
         switch (var1) {
            case 0:
               var10000 = "/res/English.txt";
               break;
            case 1:
               var10000 = "/res/Italian.txt";
               break;
            case 2:
               var10000 = "/res/French.txt";
               break;
            case 3:
               var10000 = "/res/German.txt";
               break;
            case 4:
               var10000 = "/res/Spanish.txt";
               break;
            case 5:
            default:
               break label18;
            case 6:
               var10000 = "/res/Czech.txt";
               break;
            case 7:
               var10000 = "/res/Portuguese.txt";
               break;
            case 8:
               var10000 = "/res/Turkish.txt";
         }

         var2 = var10000;
      }

      this.a = new com.vlm.redstar.client.ui.b(var2);
      this.ch = this.a.a(0);
      this.ci = this.a.a(1);
      this.cj = this.a.a(2);
      this.ck = this.a.a(3);
      c = this.a.a(4);
      d = this.a.a(5);
      e = this.a.a(6);
      f = this.a.a(7);
      g = this.a.a(8);
      h = this.a.a(9);
      i = this.a.a(10);
      j = this.a.a(11);
      k = this.a.a(12);
      l = this.a.a(13);
      m = this.a.a(14);
      n = this.a.a(15);
      o = this.a.a(16);
      p = this.a.a(17);
      q = this.a.a(18);
      r = this.a.a(19);
      s = this.a.a(20);
      t = this.a.a(21);
      u = this.a.a(22);
      v = this.a.a(23);
      w = this.a.a(24);
      x = this.a.a(25);
      y = this.a.a(26);
      z = this.a.a(27);
      A = this.a.a(28);
      B = this.a.a(29);
      C = this.a.a(30);
      D = this.a.a(31);
      E = this.a.a(32);
      F = this.a.a(33);
      G = this.a.a(34);
      H = this.a.a(35);
      I = this.a.a(36);
      J = this.a.a(37);
      K = this.a.a(38);
      L = this.a.a(39);
      M = this.a.a(40);
      this.a.a(41);
      N = this.a.a(42);
      O = this.a.a(43);
      P = this.a.a(44);
      Q = this.a.a(45);
      R = this.a.a(46);
      S = this.a.a(47);
      T = this.a.a(48);
      U = this.a.a(49);
      V = this.a.a(50);
      W = this.a.a(51);
      X = this.a.a(52);
      Y = this.a.a(53);
      Z = this.a.a(54);
      aa = this.a.a(55);
      ab = this.a.a(56);
      ac = this.a.a(57);
      ad = this.a.a(58);
      ae = this.a.a(59);
      af = this.a.a(60);
      ag = this.a.a(61);
      ah = this.a.a(62);
      ai = this.a.a(63);
      this.cl = this.a.a(64);
      this.cm = this.a.a(65);
      this.cn = this.a.a(66);
      this.co = this.a.a(67);
      this.cp = this.a.a(68);
      this.cq = this.a.a(69);
      this.cr = this.a.a(70);
      aj = this.a.a(71);
      ak = this.a.a(72);
      al = this.a.a(73) + "?";
      am = this.a.a(74);
      an = this.a.a(75);
      ao = this.a.a(76);
      ap = this.a.a(77);
      aq = this.a.a(78);
      ar = this.a.a(79);
      as = this.a.a(80);
      at = this.a.a(81);
      au = this.a.a(82);
      this.cs = this.a.a(83);
      this.ct = this.a.a(84);
      this.cu = this.a.a(85);
      this.cv = this.a.a(86);
      this.cw = this.a.a(87);
      this.cx = this.a.a(88);
      this.cy = this.a.a(89);
      this.cz = this.a.a(90);
      this.cA = this.a.a(91);
      this.cB = this.a.a(92);
      this.cC = this.a.a(93);
      av = this.a.a(94);
      this.cD = this.a.a(95);
      this.cE = this.a.a(96);
      this.cF = this.a.a(97);
      this.cG = this.a.a(98);
      this.cH = this.a.a(99);
      this.cI = this.a.a(100);
      this.cJ = this.a.a(101);
      this.cK = this.a.a(102);
      this.cL = this.a.a(103);
      this.cM = this.a.a(104);
      this.cN = this.a.a(105);
      this.cO = this.a.a(106);
      this.cP = this.a.a(107);
      this.cQ = this.a.a(108);
      this.cR = this.a.a(109);
      this.cS = this.a.a(110);
      this.cT = this.a.a(111);
      this.cU = this.a.a(112);
      this.cV = this.a.a(113);
      this.cW = this.a.a(114);
      this.cX = this.a.a(115);
      this.cY = this.a.a(116);
      this.cZ = this.a.a(117);
      this.da = this.a.a(118) + aquadig.d.a(7000, true);
      this.db = this.a.a(119) + aquadig.d.a(10000, true);
      this.dc = this.a.a(120) + aquadig.d.a(15000, true);
      this.dd = this.a.a(121);
      this.de = this.a.a(122);
      this.df = this.a.a(123) + aquadig.d.a(3000, true);
      this.dg = this.a.a(124) + aquadig.d.a(2500, true);
      this.dh = this.a.a(125);
      this.di = this.a.a(126);
      this.dj = this.a.a(127);
      this.dk = this.a.a(128);
      this.dl = this.a.a(129);
      this.dm = this.a.a(130);
      this.dn = this.a.a(131);
      this.do_ = this.a.a(132);
      aw = this.a.a(133);
      ax = this.a.a(134);
      ay = this.a.a(135);
      az = this.a.a(136);
      this.a.a(137);
      this.dp = this.a.a(138);
      this.dq = this.a.a(139);
      this.dr = this.a.a(140);
      this.ds = this.a.a(141);
      this.dt = this.a.a(142);
      this.du = this.a.a(143);
      this.dv = this.a.a(144);
      this.dw = this.a.a(145);
      this.dx = this.a.a(146);
      this.dy = this.a.a(147);
      this.dz = this.a.a(148);
      this.dA = this.a.a(149);
      this.dB = this.a.a(150);
      this.dC = this.a.a(151);
      this.dD = this.a.a(152);
      this.dE = this.a.a(153);
      this.dF = this.a.a(154);
      this.dG = this.a.a(155);
      this.dH = this.a.a(156);
      this.dI = this.a.a(157);
      this.dJ = this.a.a(158);
      this.dK = this.a.a(159);
      this.dL = this.a.a(160);
      this.dM = this.a.a(161);
      this.dN = this.a.a(162);
      aA = this.a.a(163);
      this.dO = this.a.a(164);
      this.dP = this.a.a(165);
      this.a.a(166);
      aB = this.a.a(167);
      aC = this.a.a(168);
      aD = this.a.a(169);
      aE = this.a.a(170);
      this.dQ = this.a.a(171);
      this.dR = this.a.a(172);
      this.dS = this.a.a(173);
      this.dT = this.a.a(174);
      this.dU = this.a.a(175);
      this.dV = this.a.a(176);
      this.dW = this.a.a(177);
      aF = this.a.a(178);
      aG = this.a.a(179);
      this.dX = this.a.a(180);
      this.dY = this.a.a(181);
      this.dZ = this.a.a(182);
      this.ea = this.a.a(183);
      this.eb = this.a.a(184);
      this.ec = this.a.a(185);
      this.ed = this.a.a(186);
      this.ee = this.a.a(187);
      aH = this.a.a(188);
      aI = this.a.a(189);
      aJ = this.a.a(190);
      this.ef = this.a.a(191);
      this.eg = this.a.a(192);
      this.eh = this.a.a(193);
      this.ei = this.a.a(194);
      this.ej = this.a.a(195);
      aK = this.a.a(196);
      aL = this.a.a(197);
      aM = this.a.a(198);
      aN = this.a.a(199);
      aO = this.a.a(200);
      aP = this.a.a(201);
      this.a.a(202);
      aQ = this.a.a(203);
      aR = this.a.a(204);
      aS = this.a.a(205);
      aT = this.a.a(206);
      aU = this.a.a(207);
      aV = this.a.a(208);
      aW = this.a.a(209);
      aX = this.a.a(210);
      aY = this.a.a(211);
      aZ = this.a.a(212);
      ba = this.a.a(213);
      bb = this.a.a(214);
      bc = this.a.a(215);
      bd = this.a.a(216);
      be = this.a.a(217);
      bf = this.a.a(218);
      bg = this.a.a(219);
      bh = this.a.a(220);
      bi = this.a.a(221);
      bj = this.a.a(222);
      bk = this.a.a(223);
      bl = this.a.a(224);
      this.a.a(225);
      bm = this.a.a(226);
      bn = this.a.a(227);
      bo = this.a.a(228);
      bp = this.a.a(229);
      bq = this.a.a(230);
      br = this.a.a(231);
      bs = this.a.a(232);
      bt = this.a.a(233);
      bu = this.a.a(234);
      bv = this.a.a(235);
      bw = this.a.a(236);
      bx = this.a.a(237);
      by = this.a.a(238);
      bz = this.a.a(239);
      bA = this.a.a(240);
      bB = this.a.a(241);
      bC = this.a.a(242);
      bD = this.a.a(243);
      bE = this.a.a(244);
      bF = this.a.a(245);
      bG = this.a.a(246);
      bH = this.a.a(247);
      bI = this.a.a(248);
      bJ = this.a.a(249);
      bK = this.a.a(250);
      bL = this.a.a(251);
      bM = this.ch
         + " \nDavid Kainer \nGabi Harkham \n\n"
         + this.ci
         + " \nAndrew Skinner \nDonna Trim \nIan Hosken \nJohn Murphy \nStephen Kilsby \nAntonio Rodriguez \n\n"
         + this.cj
         + " \nJames Croke \n\n"
         + this.ck
         + " \nDaniel Moore";
      bN = new String[]{this.cl, this.cm, this.cn};
      bO = new String[]{this.co, this.cp, this.cq};
      bP = this.cr + al;
      bQ = this.cr + " " + U.toLowerCase() + "?";
      bR = this.cr + ap;
      bS = B.toLowerCase();
      bT = at + " " + bS + ".";
      bU = at + " " + au + ".";
      bV = new String[]{"", this.cs, this.ct, this.cu, this.cv, this.cw, this.cx, this.cy, this.cz, this.cA, this.cB, this.cC};
      bW = new String[]{this.cD, this.cE, this.cF, this.cG, this.cH, this.cI, this.cJ, this.cK, this.cL, this.cM, this.cN};
      bX = new String[]{this.cO, this.cP, this.cQ, this.cR, this.cS, this.cT, this.cU, this.cV, this.cW, this.cX, this.cY};
      bY = new String[]{this.cZ, this.da, this.db, this.dc, this.dd, this.de, this.df, this.dg, this.dh, this.di, this.dj};
      bZ = new String[]{this.dk, this.dl, this.dm, this.dn, this.do_};
      ca = new String[]{this.dp, this.dq, this.dr, this.ds, this.dt};
      cb = new String[][]{
         {"", this.du, this.dv, this.dw, this.dx},
         {"", this.dy, this.dz, this.dA, this.dB},
         {"", this.dC, this.dD, this.dE, this.dF},
         {"", this.dG, this.dH, this.dI, this.dJ},
         {"", this.dK, this.dL, this.dM, this.dN}
      };
      cc = new String[]{this.dO, this.dP};
      cd = new String[]{aC + bN[0] + aE + b[0], aD + bN[1] + aE + b[1], aD + bN[2] + aE + b[2]};
      ce = new String[]{this.dQ, this.dR, this.dS, this.dT, this.dU, this.dV, this.dW};
      cf = new String[]{this.dX, this.dY, this.dZ, this.ea, this.eb, this.ec, this.ed, this.ee};
      cg = new String[]{this.ef, this.eg, this.eh, this.ei, this.ej};
      this.ch = null;
      this.ci = null;
      this.cj = null;
      this.ck = null;
      this.cl = null;
      this.cm = null;
      this.cn = null;
      this.co = null;
      this.cp = null;
      this.cq = null;
      this.cr = null;
      this.cs = null;
      this.ct = null;
      this.cu = null;
      this.cv = null;
      this.cw = null;
      this.cx = null;
      this.cy = null;
      this.cz = null;
      this.cA = null;
      this.cB = null;
      this.cC = null;
      this.cD = null;
      this.cE = null;
      this.cF = null;
      this.cG = null;
      this.cH = null;
      this.cI = null;
      this.cJ = null;
      this.cK = null;
      this.cL = null;
      this.cM = null;
      this.cN = null;
      this.cO = null;
      this.cP = null;
      this.cQ = null;
      this.cR = null;
      this.cS = null;
      this.cT = null;
      this.cU = null;
      this.cV = null;
      this.cW = null;
      this.cX = null;
      this.cY = null;
      this.cZ = null;
      this.da = null;
      this.db = null;
      this.dc = null;
      this.dd = null;
      this.de = null;
      this.df = null;
      this.dg = null;
      this.dh = null;
      this.di = null;
      this.dj = null;
      this.dk = null;
      this.dl = null;
      this.dm = null;
      this.dn = null;
      this.do_ = null;
      this.dp = null;
      this.dq = null;
      this.dr = null;
      this.ds = null;
      this.dt = null;
      this.du = null;
      this.dv = null;
      this.dw = null;
      this.dx = null;
      this.dy = null;
      this.dz = null;
      this.dA = null;
      this.dB = null;
      this.dC = null;
      this.dD = null;
      this.dE = null;
      this.dF = null;
      this.dG = null;
      this.dH = null;
      this.dI = null;
      this.dJ = null;
      this.dK = null;
      this.dL = null;
      this.dM = null;
      this.dN = null;
      this.dO = null;
      this.dP = null;
      this.dQ = null;
      this.dR = null;
      this.dS = null;
      this.dT = null;
      this.dU = null;
      this.dV = null;
      this.dW = null;
      this.dX = null;
      this.dY = null;
      this.dZ = null;
      this.ea = null;
      this.eb = null;
      this.ec = null;
      this.ed = null;
      this.ee = null;
      this.ef = null;
      this.eg = null;
      this.eh = null;
      this.ei = null;
      this.ej = null;
   }

   public static void a() {
      System.gc();
   }
}
